env:
  node: true

extends: 'eslint:recommended'

parserOptions:
  ecmaVersion: 5

rules:

  # Style
  indent:          [ error, tab, { SwitchCase: 1 }]
  linebreak-style: [ error, unix ]
  quotes:          [ error, single ]
  semi:            [ error, always ]
  camelcase:       [ error ]

  # Additional rules
  strict:                       [ error, global ]
  curly:                        [ error, all ]
  eqeqeq:                       [ error, always ]
  guard-for-in:                 [ error ]
  no-alert:                     [ error ]
  no-eval:                      [ error ]
  no-extend-native:             [ error ]
  no-floating-decimal:          [ error ]
  no-implicit-coercion:         [ error ]
  no-implied-eval:              [ error ]
  no-invalid-this:              [ error ]
  no-labels:                    [ error ]
  no-loop-func:                 [ error ]
  no-new:                       [ error ]
  no-new-func:                  [ error ]
  no-new-wrappers:              [ error ]
  no-return-assign:             [ error, always ]
  no-script-url:                [ error ]
  no-self-compare:              [ error ]
  no-throw-literal:             [ error ]
  no-unmodified-loop-condition: [ error ]
  no-unused-expressions:        [ error ]
  no-useless-concat:            [ error ]
  no-useless-return:            [ error ]
  no-warning-comments:          [ warn, { location: anywhere, terms: [ TODO ] }]
  no-shadow:                    [ error, { builtinGlobals: true }]
  no-shadow-restricted-names:   [ error ]

  # Relaxed rules
  no-redeclare:          [ off ]
  no-constant-condition: [ error, { checkLoops: false }]

